"""sua enum ApplicationStatus

Revision ID: 9fc7109fe6a6
Revises: 07396458e540
Create Date: 2026-09-10 18:56:46.854396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fc7109fe6a6'
down_revision = '07396458e540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'REVIEWED', 'SHORTLISTED', 'REJECTED'),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'),
               type_=mysql.ENUM('PENDING', 'REVIEWED', 'SHORTLISTED', 'REJECTED'),
               existing_nullable=False)

    # ### end Alembic commands ###
